name: XNEON Recovery Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "XNEON Recovery Build Started"
          uname -a
